### ISSUE TITLE
An error occurred while compiling the code

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1062] opened 2020-01-07 07:34 UTC
An error occurred while compiling the code.
commitid：fc4f5d23498032f50cc6ee3ac0fb44d189e5bdae
--------------------------------------------------------------------------------------
15:02:58 ln -s success.
15:03:02 >>> /opt/go1.11.3/bin/go install -ldflags -X main.gitCommit=fc4f5d23498032f50cc6ee3ac0fb44d189e5bdae -v ./cmd/platon
15:03:02 github.com/PlatONnetwork/PlatON-Go/x/xcom
15:03:03 # github.com/PlatONnetwork/PlatON-Go/x/xcom
15:03:03 x/xcom/common_config.go:275:5: unknown field 'HesitateRatio' in struct literal of type stakingConfig
15:03:03 x/xcom/common_config.go:321:5: unknown field 'HesitateRatio' in struct literal of type stakingConfig
15:03:03 x/xcom/common_config.go:367:5: unknown field 'HesitateRatio' in struct literal of type stakingConfig
15:03:03 util.go:45: exit status 2
15:03:03 exit status 1
15:03:03 Build step 'Execute shell' marked build as failure
15:03:03 Finished: FAILURE

**Comment by benbaley** [comment] 2020-01-07 12:02
This is a bug caused by merging 'feature/bump-version-to-0.7.5.2' 
and have been fixed in latest version

**Closed** 2020-01-08 09:21 UTC
Labels: P1, bug
